### ISSUE TITLE
npm start异常

### ISSUE THREAD

**Issue by DengKe1994** [weui/react-weui#93]
/Users/dengka/code/react-weui/node_modules/extract-text-webpack-plugin/index.js:118
	Object.keys(b).forEach(function(key) {
	       ^
TypeError: Object.keys called on non-object
    at Function.keys (native)
    at mergeOptions (/Users/dengka/code/react-weui/node_modules/extract-text-webpack-plugin/index.js:118:9)
    at Function.ExtractTextPlugin.extract (/Users/dengka/code/react-weui/node_modules/extract-text-webpack-plugin/index.js:134:29)
    at Object.<anonymous> (/Users/dengka/code/react-weui/webpack.config.js:29:43)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at module.exports (/Users/dengka/code/react-weui/node_modules/webpack/bin/convert-argv.js:80:13)
    at Object.<anonymous> (/Users/dengka/code/react-weui/node_modules/webpack-dev-server/bin/webpack-dev-server.js:55:48)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

**Comment by progrape** [comment]
@DengKe1994 node 版本是？

**Comment by DengKe1994** [comment]
v0.12.7

**Comment by DengKe1994** [comment]
@progrape v0.12.7

**Comment by progrape** [comment]
@DengKe1994 建议使用 >= 4.0 的版本

**Comment by DengKe1994** [comment]
Thx
